Repository hubmapconsortium/ccf-ui, pull requests merged in 2020-03, with the labels that each got.

#165 PBI 130 infobutton
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/core/header/header.component.html
  src/app/core/header/header.component.scss
  src/app/core/header/header.component.theme.scss
  src/app/core/header/header.module.ts
  src/app/modules/info/info-button/info-button.component.html
  src/app/modules/info/info-button/info-button.component.scss
  src/app/modules/info/info-button/info-button.component.spec.ts
  src/app/modules/info/info-button/info-button.component.ts
  src/app/modules/info/info-button/info-button.module.ts
  src/app/modules/info/info-dialog/info-dialog.component.html
  src/app/modules/info/info-dialog/info-dialog.component.scss
  src/app/modules/info/info-dialog/info-dialog.component.spec.ts
  src/app/modules/info/info-dialog/info-dialog.component.ts
  src/app/modules/info/info-dialog/info-dialog.module.ts
  src/assets/images/nih_master_logo.svg
Labels: user-story

#173 PBI 143 filter animation
  src/app/modules/filters/filters-popover/filters-popover.component.html
  src/app/modules/filters/filters-popover/filters-popover.component.scss
  src/app/modules/filters/filters-popover/filters-popover.component.ts
Labels: user-story

#172 Misc. User Stories from Sprint 1
  src/app/modules/filters/filters-popover/filters-popover.component.scss
  src/app/modules/ontology-exploration/ontology-search/ontology-search.component.scss
  src/app/shared/components/checkbox/checkbox.component.scss
  src/app/shared/components/checkbox/checkbox.component.theme.scss
  src/app/shared/components/drawer/drawer.theme.scss
  src/themes/common/_theming.scss
Labels: General UI, Partonomy, Tissue Browser, user-story

#184 tests + documentation for filters-content
  src/app/modules/filters/filters-content/filters-content.component.html
  src/app/modules/filters/filters-content/filters-content.component.spec.ts
  src/app/modules/filters/filters-content/filters-content.component.ts
Labels: Tissue Browser

#183 testing / documentation of filters-popover
  src/app/modules/filters/filters-popover/filters-popover.component.spec.ts
  src/app/modules/filters/filters-popover/filters-popover.component.ts
Labels: Tissue Browser

#186 Test document info dialog
  src/app/modules/info/info-dialog/info-dialog.component.spec.ts
  src/app/modules/info/info-dialog/info-dialog.component.ts
Labels: General UI

#185 Testing header
  src/app/core/header/header.component.html
  src/app/core/header/header.component.spec.ts
  src/app/core/header/header.component.ts
  src/app/core/header/header.module.ts
Labels: General UI

#188 documentation for the checkbox component
  src/app/shared/components/checkbox/checkbox.component.ts
Labels: Tissue Browser

#187 Testing info button
  src/app/modules/info/info-button/info-button.component.spec.ts
Labels: General UI
